### ISSUE TITLE
Mention recommended newer crypto algorithms?

### ISSUE THREAD

**Issue by he32** [paulehoffman/draft-hoffman-dnssec#1]
At the end of the starting part of section 2, should references be given to the more "modern" and "recommended to implement" crypto algorithms to be considered to be "reasonably modern"?  I'm thinking of e.g. sha-2 and some of the EC variants.

**Comment by he32** [comment]
Hmm, I see this is covered in section 2.1.  Perhaps add a sentence at the end of section 2 along "However, see the section below for more recommended-to-implement crypto algorithms."

**Comment by paulehoffman** [comment]
Given that 2.1 comes right after 2.2, this seems unnecessary. I think it would be better to leave 2 as the description of just the original core, followed immediately by extensions to the original core.
