### ISSUE TITLE
Adding additional RFCs

### ISSUE THREAD

**Issue by paulehoffman** [paulehoffman/draft-hoffman-dnssec#5]
On-list, Joey Deng @dengqiaoyu said:
During my reading of DNS and DNSSEC, I found another RFC (RFC 7129) very helpful in understanding the motivation from NSEC to NSEC3, besides RFC 5155, but it is not listed in the draft above (maybe because it is for informational purposes?).
https://datatracker.ietf.org/doc/rfc7129/

**Comment by paulehoffman** [comment]
I replied:
While RFC 7129 is interesting for understanding the protocol, it is background material and maybe not really part of the protocol itself or an extension to the protocol itself. I'm not sure where it would fit into this document.

Peter Thomassen @peterthomassen replied:
The purpose is to introduce all of the RFCs in one place so
that the reader can understand the many aspects of DNSSEC.

I think Peter has a good argument, and I think that adding a new section with the vague title "Additional RFCs Related to DNSSEC" might work.

**Comment by moonshiner** [comment]
Would these also fall into this section:

rfc8901  Multi-Signer DNSSEC Models

rfc7583 DNSSEC Key Rollover Timing Considerations

**Comment by paulehoffman** [comment]
They could, yes. We could, if we wanted, also list protocols that are known to require DNSSEC signing (such as TLSA).

This would be a good WG discussion.

**Comment by moonshiner** [comment]
Will chew on this - my first thought "let's make a list and check yes/no" and was like "Paul's already done that"

The TLSA is nice idea too.

**Comment by moonshiner** [comment]
This is incredibly lame and feel free to mock, but everything from rfc-editor.org that mentions DNSSEC

https://docs.google.com/spreadsheets/d/1ekuaHVScJwc-PmfDVzOWBVUqaElWQdFtJn8DkMvweHk/edit?usp=sharing

**Comment by paulehoffman** [comment]
Consider it mocked. :-) The reader of this BCP wants to know what goes into the BCP and maybe (still not sure) what is closely related.

**Comment by moonshiner** [comment]
Agreed that only closely related docs should be included.  This can be used as a sign of a mocking level of due diligence. 

welcome to have access to mark yes/no

**Comment by moonshiner** [comment]
Also consider this list as something to attach to the shepherd write up to show the IESG and the Area Reviews completeness.

**Comment by paulehoffman** [comment]
Closed by #7 , will be in next draft.
