### ISSUE TITLE
Mention RFC 4592?

### ISSUE THREAD

**Issue by miekg** [paulehoffman/draft-hoffman-dnssec#8]
Should https://www.rfc-editor.org/info/rfc4592 (wildcards in the DNS) get a mention in the BCP?

I've understood NSEC/NSEC3 much better with document in my mind.

Of course: this isn't a DNSSEC document, so that might open a can of worms

**Comment by paulehoffman** [comment]
It is not DNSSEC, and I came across a few others that could fit into that can, but I bet there are a zillion more. A year from now (maybe sooner), I hope to have a different project that you'll like that will deal with "what are all the RFCs for the DNS, but show me them in a useful fashion".
